services:
  db:
    image: postgres:16
    container_name: clothing-store-db
    environment:
      POSTGRES_DB: clothing_store
      POSTGRES_USER: clothing_user
      POSTGRES_PASSWORD: clothing_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrate-schema.sql:/docker-entrypoint-initdb.d/01-migrate-schema.sql
      - ./db/sample-data.sql:/docker-entrypoint-initdb.d/02-sample-data.sql

  fastapi-app:
    build:
      context: .
    container_name: clothing-store-api
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: "1"
      MODE: ${MODE:-development}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    volumes:
      - ./app:/code/app
      - ./db:/code/db
      - ./db_migration.py:/code/db_migration.py
    ports:
      - "8080:8080"

volumes:
  postgres_data:
